### ISSUE TITLE
Get HTTPS for meddelare.com

### ISSUE THREAD

**Issue by joelpurra** [meddelare/meddelare-superproject#5]
It doesn't seem as it github allows use of HTTPS for custom (`CNAME`'d) domains. This causes problems when including resources from other domains, as well as isn't great when trying to promote privacy.

Also see #1.

**Comment by thomasdavis** [comment]
You could throw Cloudflare in front of it for free https.

I believe them to have decent privacy, they don't even store logs because it's technically not feasible =D

**Comment by joelpurra** [comment]
@thomasdavis: that would be the quick solution, yes. Already have a Cloudfront distribution in front of the API to test their cache/proxy. I'll check it out. HTTPS is better than no HTTPS.

**Edit:** Cloudflare and Cloudfront have very similar names. I'll check both out to see if they're a fit in this case, just to be sure ;)

Could also add meddelare.com as a new app with a custom domain with HTTPS on Heroku. This would make sense to use with meddelare-node-express now that the API has an in-memory cache, but also mean a bit more maintenance work.

_Privacy rant:_ while Heroku, Cloudflare, Amazon/Cloudfront and other CDNs aren't social networks, using them (and other third-party services) is also a kind of privacy leak in a strict sense (especially with HTTPS termination, officially keeping logs or no logs). I am personally leaning towards getting a (more) private server to host all services I use. Ya' know, "soon".

**Comment by joelpurra** [comment]
@thomasdavis: went with Cloudflare, so HTTPS should now be enabled. Will search/replace relevant links, then possibly enable HSTS. Thanks!

**Comment by joelpurra** [comment]
Done.

Unfortunately it seems as if Twitter's share counters have now been reset despite redirects from HTTP to HTTPS. Will see if it kicks back in later, but for now we're back to square/share 0! =)
